import * as XLSX from 'xlsx';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import type { DashboardData, ExpenseInput, Item, Party, ProductionInput, PurchaseInput, SaleInput, StockBalance } from './types';

const file = join(process.cwd(), 'data', 'inventory.xlsx');
const tabs: Record<string, string[]> = { Suppliers: ['id','name','phone','contactPerson','address','active'], Customers: ['id','name','phone','contactPerson','address','customerType','active'], Items: ['id','name','type','baseUnit','reorderLevel','active'], Recipes: ['id','productId','materialId','quantity','unit','active'], PriceHistory: ['id','itemId','priceType','unit','pricePaise','effectiveFrom','active'], PurchaseInvoices: ['id','date','supplierId','billNumber','billAmountPaise','paidAmountPaise','note','status'], PurchaseLines: ['id','invoiceId','itemId','quantity','unit','unitPricePaise','totalPaise'], ProductionBatches: ['id','date','productId','quantityProduced','team','note','status'], ProductionConsumption: ['id','batchId','itemId','quantity','unit'], SalesInvoices: ['id','date','customerId','saleType','totalPaise','paidAmountPaise','note','status'], SalesLines: ['id','invoiceId','itemId','quantity','unit','unitPricePaise','totalPaise'], Expenses: ['id','date','category','amountPaise','employeeOrTeam','employeeCount','note'], StockMovements: ['id','date','itemId','quantity','unit','direction','unitCostPaise','sourceType','sourceId','note'], AuditLog: ['id','timestamp','action','entityType','entityId','actor','idempotencyKey'] };
const today = () => new Date().toISOString().slice(0, 10); const n = (v: unknown) => Number(v || 0); const money = (v: unknown) => n(v);
function saveBook(book: XLSX.WorkBook) { const temporary = `${file}.tmp`; writeFileSync(temporary, XLSX.write(book, { bookType: 'xlsx', type: 'buffer' })); renameSync(temporary, file); }
function loadBook() { return XLSX.read(readFileSync(file), { type: 'buffer' }); }
function ensure() { mkdirSync(join(process.cwd(), 'data'), { recursive: true }); if (!existsSync(file)) { const book = XLSX.utils.book_new(); for (const [name, headers] of Object.entries(tabs)) XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([headers]), name); saveBook(book); return; } const book = loadBook(); let changed = false; for (const [name, headers] of Object.entries(tabs)) if (!book.SheetNames.includes(name)) { XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([headers]), name); changed = true; } if (changed) saveBook(book); }
function read(tab: string): Record<string, string>[] { ensure(); const book = loadBook(); const sheet = book.Sheets[tab]; if (!sheet) return []; return XLSX.utils.sheet_to_json<Record<string, string>>(sheet, { defval: '' }); }
function write(tab: string, rows: Record<string, unknown>[]) { ensure(); const book = loadBook(); const headers = tabs[tab]; book.Sheets[tab] = XLSX.utils.json_to_sheet(rows, { header: headers }); if (!book.SheetNames.includes(tab)) XLSX.utils.book_append_sheet(book, book.Sheets[tab], tab); saveBook(book); }
function append(tab: string, rows: Record<string, unknown>[]) { write(tab, [...read(tab), ...rows]); }
export const sheetsConfigured = () => true;
export async function initializeWorkbook() { ensure(); return { file }; }
const item = (r: Record<string, string>): Item => ({ id: r.id, name: r.name, type: r.type as Item['type'], baseUnit: r.baseUnit, reorderLevel: n(r.reorderLevel), active: r.active !== 'false' });
const party = (r: Record<string, string>, type: Party['type']): Party => ({ id: r.id, name: r.name, phone: r.phone, contactPerson: r.contactPerson, address: r.address, type, customerType: r.customerType as Party['customerType'] });
export async function masterData() { return { suppliers: read('Suppliers').map(r => party(r, 'SUPPLIER')), customers: read('Customers').map(r => party(r, 'CUSTOMER')), items: read('Items').map(item).filter(row => row.active) }; }
export async function addMaster(kind: 'supplier'|'customer'|'item', input: Record<string, unknown>) { const id = randomUUID(); const tab = kind === 'supplier' ? 'Suppliers' : kind === 'customer' ? 'Customers' : 'Items'; append(tab, [{ id, ...input, active: 'true' }]); return id; }
async function balances() { const map = new Map<string, StockBalance>(); for (const row of read('StockMovements')) { const b = map.get(row.itemId) || { itemId: row.itemId, quantity: 0, averageCostPaise: 0 }; const q = n(row.quantity), cost = n(row.unitCostPaise); if (row.direction === 'IN') { const total = b.quantity + q; b.averageCostPaise = total ? Math.round((b.quantity * b.averageCostPaise + q * cost) / total) : 0; b.quantity = total; } else b.quantity -= q; map.set(row.itemId, b); } return map; }
async function audit(action: string, entityType: string, entityId: string) { append('AuditLog', [{ id: randomUUID(), timestamp: new Date().toISOString(), action, entityType, entityId, actor: 'admin', idempotencyKey: randomUUID() }]); }
export async function postPurchase(input: PurchaseInput) { const id = randomUUID(); append('PurchaseInvoices', [{ id, date: input.date, supplierId: input.supplierId, billNumber: input.billNumber || '', billAmountPaise: input.billAmountPaise, paidAmountPaise: input.paidAmountPaise, note: input.note || '', status: 'POSTED' }]); append('PurchaseLines', input.lines.map(line => ({ id: randomUUID(), invoiceId: id, itemId: line.itemId, quantity: line.quantity, unit: line.unit, unitPricePaise: line.unitPricePaise, totalPaise: line.quantity * line.unitPricePaise }))); append('StockMovements', input.lines.map(line => ({ id: randomUUID(), date: input.date, itemId: line.itemId, quantity: line.quantity, unit: line.unit, direction: 'IN', unitCostPaise: line.unitPricePaise, sourceType: 'PURCHASE', sourceId: id, note: input.note || '' }))); await audit('POST', 'PURCHASE', id); return { id, totalPaise: input.billAmountPaise, outstandingPaise: input.billAmountPaise - input.paidAmountPaise }; }
export async function postProduction(input: ProductionInput) { const id = randomUUID(); const stock = await balances(); let cost = 0; for (const line of input.consumption) { const b = stock.get(line.itemId); if (!b || b.quantity < line.quantity) throw new Error('Insufficient raw-material stock for this production batch.'); cost += line.quantity * b.averageCostPaise; } append('ProductionBatches', [{ id, date: input.date, productId: input.productId, quantityProduced: input.quantityProduced, team: input.team || '', note: input.note || '', status: 'POSTED' }]); append('ProductionConsumption', input.consumption.map(line => ({ id: randomUUID(), batchId: id, itemId: line.itemId, quantity: line.quantity, unit: line.unit }))); append('StockMovements', [...input.consumption.map(line => ({ id: randomUUID(), date: input.date, itemId: line.itemId, quantity: line.quantity, unit: line.unit, direction: 'OUT', unitCostPaise: stock.get(line.itemId)!.averageCostPaise, sourceType: 'PRODUCTION', sourceId: id, note: input.note || '' })), { id: randomUUID(), date: input.date, itemId: input.productId, quantity: input.quantityProduced, unit: 'piece', direction: 'IN', unitCostPaise: input.quantityProduced ? Math.round(cost / input.quantityProduced) : 0, sourceType: 'PRODUCTION', sourceId: id, note: input.note || '' }]); await audit('POST', 'PRODUCTION', id); return { id, costPaise: cost }; }
export async function postSale(input: SaleInput) { const id = randomUUID(); const stock = await balances(); const total = input.lines.reduce((s, line) => s + line.quantity * line.unitPricePaise, 0); for (const line of input.lines) { const b = stock.get(line.itemId); if (!b || b.quantity < line.quantity) throw new Error('Insufficient finished-goods stock.'); } append('SalesInvoices', [{ id, date: input.date, customerId: input.customerId, saleType: input.saleType, totalPaise: total, paidAmountPaise: input.paidAmountPaise, note: input.note || '', status: 'POSTED' }]); append('SalesLines', input.lines.map(line => ({ id: randomUUID(), invoiceId: id, itemId: line.itemId, quantity: line.quantity, unit: line.unit, unitPricePaise: line.unitPricePaise, totalPaise: line.quantity * line.unitPricePaise }))); append('StockMovements', input.lines.map(line => ({ id: randomUUID(), date: input.date, itemId: line.itemId, quantity: line.quantity, unit: line.unit, direction: 'OUT', unitCostPaise: stock.get(line.itemId)!.averageCostPaise, sourceType: 'SALE', sourceId: id, note: input.note || '' }))); await audit('POST', 'SALE', id); return { id, totalPaise: total, outstandingPaise: total - input.paidAmountPaise }; }
export async function postExpense(input: ExpenseInput) { const id = randomUUID(); append('Expenses', [{ id, date: input.date, category: input.category, amountPaise: input.amountPaise, employeeOrTeam: input.employeeOrTeam || '', employeeCount: input.employeeCount || 0, note: input.note || '' }]); await audit('POST', 'EXPENSE', id); return { id }; }
export async function purchaseHistory(date: string) { const [invoices, lines, master] = await Promise.all([read('PurchaseInvoices'), read('PurchaseLines'), masterData()]); const names = new Map(master.items.map(i => [i.id, i.name])); const bills = invoices.filter(r => r.date === date).map(r => ({ id: r.id, supplierId: r.supplierId, supplier: master.suppliers.find(s => s.id === r.supplierId)?.name || r.supplierId, billNumber: r.billNumber, billAmountPaise: money(r.billAmountPaise), paidAmountPaise: money(r.paidAmountPaise), pendingPaise: Math.max(0, money(r.billAmountPaise) - money(r.paidAmountPaise)), lines: lines.filter(l => l.invoiceId === r.id).map(l => ({ name: names.get(l.itemId) || l.itemId, quantity: n(l.quantity), unit: l.unit, totalPaise: money(l.totalPaise) })) })); const supplierSummary = master.suppliers.map(supplier => { const own = invoices.filter(invoice => invoice.supplierId === supplier.id); return { supplierId: supplier.id, billCount: own.length, totalPaise: own.reduce((sum, invoice) => sum + money(invoice.billAmountPaise), 0), pendingPaise: own.reduce((sum, invoice) => sum + Math.max(0, money(invoice.billAmountPaise) - money(invoice.paidAmountPaise)), 0) }; }); return { bills, supplierSummary, summary: { totalPaise: bills.reduce((s, b) => s + b.billAmountPaise, 0), billCount: bills.length, overallOutstandingPaise: invoices.reduce((s, invoice) => s + Math.max(0, money(invoice.billAmountPaise) - money(invoice.paidAmountPaise)), 0), overallPurchasedPaise: invoices.reduce((s, invoice) => s + money(invoice.billAmountPaise), 0), overallBillCount: invoices.length } }; }
export async function dashboard(): Promise<DashboardData> { const master = await masterData(); const stock = await balances(); const raw = master.items.filter(i => i.type === 'RAW_MATERIAL'); const lowStock = raw.map(i => ({ item: i, quantity: stock.get(i.id)?.quantity || 0 })).filter(r => r.quantity <= r.item.reorderLevel); const purchases = read('PurchaseInvoices'), sales = read('SalesInvoices'), expenses = read('Expenses'), production = read('ProductionBatches'); const d = today(); const purchase = purchases.filter(r => r.date === d).reduce((s, r) => s + money(r.billAmountPaise), 0), sale = sales.filter(r => r.date === d).reduce((s, r) => s + money(r.totalPaise), 0), expense = expenses.filter(r => r.date === d).reduce((s, r) => s + money(r.amountPaise), 0); return { generatedAt: new Date().toISOString(), configured: true, cards: { rawMaterialValuePaise: raw.reduce((s, i) => s + (stock.get(i.id)?.quantity || 0) * (stock.get(i.id)?.averageCostPaise || 0), 0), lowStockCount: lowStock.length, todayPurchasePaise: purchase, todayProductionUnits: production.filter(r => r.date === d).reduce((s, r) => s + n(r.quantityProduced), 0), todaySalesPaise: sale, supplierOutstandingPaise: purchases.reduce((s, r) => s + Math.max(0, money(r.billAmountPaise) - money(r.paidAmountPaise)), 0), customerOutstandingPaise: sales.reduce((s, r) => s + Math.max(0, money(r.totalPaise) - money(r.paidAmountPaise)), 0), todayExpensePaise: expense, todayProfitPaise: sale - expense }, lowStock, topProducts: [], recentActivity: [] }; }
