'use client';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import type { DashboardData, Item, Party } from '@/lib/inventory/types';

const today = () => new Date().toISOString().slice(0, 10);
const money = (value = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value / 100);
const empty: DashboardData = { generatedAt: '', configured: false, cards: { rawMaterialValuePaise: 0, lowStockCount: 0, todayPurchasePaise: 0, todayProductionUnits: 0, todaySalesPaise: 0, supplierOutstandingPaise: 0, customerOutstandingPaise: 0, todayExpensePaise: 0, todayProfitPaise: 0 }, lowStock: [], topProducts: [], recentActivity: [] };
type View = 'Dashboard' | 'Purchases' | 'Customers' | 'Production' | 'Expenses';
type PurchaseLine = { name: string; quantity: string; unit: string; price: string };
const newLine = (): PurchaseLine => ({ name: '', quantity: '', unit: 'kg', price: '' });

export default function OperationalApp() {
  const [view, setView] = useState<View>('Dashboard'); const [dashboard, setDashboard] = useState(empty); const [items, setItems] = useState<Item[]>([]); const [suppliers, setSuppliers] = useState<Party[]>([]); const [customers, setCustomers] = useState<Party[]>([]); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const refresh = useCallback(async () => { const [dash, master] = await Promise.all([fetch('/api/inventory/dashboard'), fetch('/api/inventory/master')]); if (dash.ok) setDashboard(await dash.json()); else setError((await dash.json()).error || 'Unable to load the inventory dashboard.'); if (master.ok) { const data = await master.json(); setItems(data.items); setSuppliers(data.suppliers); setCustomers(data.customers); } }, []);
  useEffect(() => { refresh(); }, [refresh]);
  async function save(path: string, body: unknown) { setError(''); setNotice(''); const response = await fetch(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Could not save this record.'); return false; } setNotice('Saved successfully.'); await refresh(); return true; }
  async function setup() { if (await save('/api/inventory/setup', {})) setNotice('Workbook initialized. Start by adding a supplier or customer from the relevant screen.'); }
  async function logout() { await fetch('/api/inventory/auth/logout', { method: 'POST' }); window.location.assign('/inventory-management/login'); }
  return <main className="im-app"><aside className="im-sidebar"><a href="/" className="im-brand"><span>MRJ</span><small>BEST BAKERY</small></a>{(['Dashboard', 'Purchases', 'Customers', 'Production', 'Expenses'] as View[]).map(name => <button className={view === name ? 'active' : ''} onClick={() => setView(name)} key={name}>{name}</button>)}<div className="im-sidebar-bottom"><span>Signed in as admin</span><button onClick={logout}>Sign out</button></div></aside><section className="im-workspace"><header className="im-topbar"><div><p className="im-kicker">INVENTORY CONTROL</p><h1>{view}</h1></div><span className="im-date">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'full' }).format(new Date())}</span></header>{notice && <div className="im-notice">✓ {notice}</div>}{error && <div className="im-error im-banner">{error}</div>}{view === 'Dashboard' && <Dashboard data={dashboard} setup={setup} />}{view === 'Purchases' && <PurchaseWorkspace suppliers={suppliers} items={items} save={save} />}{view === 'Customers' && <CustomerWorkspace customers={customers} items={items} save={save} />}{view === 'Production' && <ProductionHint />}{view === 'Expenses' && <ExpenseForm save={save} />}</section></main>;
}
function Dashboard({ data, setup }: { data: DashboardData; setup: () => void }) { const values = [['Raw-material value', money(data.cards.rawMaterialValuePaise)], ['Low stock', String(data.cards.lowStockCount)], ['Today’s purchases', money(data.cards.todayPurchasePaise)], ['Today’s sales', money(data.cards.todaySalesPaise)], ['Supplier due', money(data.cards.supplierOutstandingPaise)], ['Customer due', money(data.cards.customerOutstandingPaise)]]; return <>{!data.configured && <section className="im-setup"><div><p className="im-kicker">FIRST-TIME SETUP</p><h2>Initialize local Excel workbook</h2><p>Create data/inventory.xlsx with the inventory tabs once, then start from Purchases or Customers.</p></div><button onClick={setup}>Create workbook →</button></section>}<div className="im-card-grid">{values.map(([label, value]) => <article className="im-stat" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></>; }
function PurchaseWorkspace({ suppliers, items, save }: { suppliers: Party[]; items: Item[]; save: (path: string, body: unknown) => Promise<boolean> }) { const [date, setDate] = useState(today()); const [activity, setActivity] = useState<{ bills: Bill[]; supplierSummary: Array<{ supplierId: string; billCount: number; totalPaise: number; pendingPaise: number }>; summary: { totalPaise: number; billCount: number; overallOutstandingPaise: number; overallPurchasedPaise: number; overallBillCount: number } }>({ bills: [], supplierSummary: [], summary: { totalPaise: 0, billCount: 0, overallOutstandingPaise: 0, overallPurchasedPaise: 0, overallBillCount: 0 } }); const [selected, setSelected] = useState<Party | null>(null); const [creating, setCreating] = useState(false); const [modal, setModal] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/inventory/purchases?date=${date}`); if (response.ok) setActivity(await response.json()); }, [date]); useEffect(() => { load(); }, [load]);
  async function addSupplier(form: FormData) { if (await save('/api/inventory/master', { kind: 'supplier', data: { name: form.get('name'), phone: form.get('phone'), contactPerson: form.get('contactPerson'), address: form.get('address') } })) setModal(false); }
  const partyBills = selected ? activity.bills.filter(bill => bill.supplierId === selected.id) : []; const selectedSummary = selected ? activity.supplierSummary.find(row => row.supplierId === selected.id) : undefined;
  return <div className="im-operational"><DateStrip date={date} setDate={setDate} />{selected ? <section className="im-selected-party"><div className="im-selected-party-head"><div><p className="im-kicker">SUPPLIER ACCOUNT</p><h2>{selected.name}</h2><span>{selected.contactPerson || selected.phone || selected.address || 'Purchase account'}</span></div><button className="im-secondary" onClick={() => { setSelected(null); setCreating(false); }}>← All suppliers</button></div><div className="im-party-summary"><span><b>{selectedSummary?.billCount || 0}</b> total bills</span><span><b>{money(selectedSummary?.totalPaise || 0)}</b> total purchased</span><span><b>{money(selectedSummary?.pendingPaise || 0)}</b> pending</span><button onClick={() => setCreating(true)}>+ New bill for {selected.name}</button></div></section> : <><section className="im-summary-row"><span><b>{activity.summary.overallBillCount}</b> total bills</span><span><b>{money(activity.summary.overallPurchasedPaise)}</b> total purchased</span><span><b>{money(activity.summary.overallOutstandingPaise)}</b> overall supplier balance</span></section><div className="im-workspace-head"><div><p className="im-kicker">CHOOSE A SUPPLIER</p><h2>Purchase accounts</h2></div><button onClick={() => setModal(true)}>+ New supplier</button></div><div className="im-party-cards">{suppliers.map(supplier => { const summary = activity.supplierSummary.find(row => row.supplierId === supplier.id); return <button className="im-party-card" key={supplier.id} onClick={() => setSelected(supplier)}><span>{supplier.name.slice(0, 1)}</span><b>{supplier.name}</b><small>{supplier.contactPerson || supplier.phone || 'Open supplier'}</small><em>{summary?.billCount || 0} bills · {money(summary?.totalPaise || 0)} purchased</em><strong>{money(summary?.pendingPaise || 0)} pending</strong></button>; })}{!suppliers.length && <Empty title="No suppliers yet" copy="Create your first supplier without leaving this screen." />}</div></>}{selected && creating && <PurchaseBill supplier={selected} items={items} save={save} done={() => { setCreating(false); load(); }} />}{selected && <section className="im-bill-list"><div className="im-panel-title"><h2>{date === today() ? `Bills today · ${selected.name}` : `Bills on ${date}`}</h2><span>{partyBills.length} bills</span></div>{partyBills.length ? partyBills.map(bill => <BillCard bill={bill} key={bill.id} />) : <Empty title="No bills for this date" copy={`Use “New bill for ${selected.name}” to record a purchase.`} />}</section>}<Modal open={modal} title="New supplier" close={() => setModal(false)}><PartyForm kind="supplier" submit={addSupplier} /></Modal></div>; }
type Bill = { id: string; supplierId: string; supplier: string; billNumber: string; billAmountPaise: number; paidAmountPaise: number; pendingPaise: number; lines: Array<{ name: string; quantity: number; unit: string; totalPaise: number }> };
function PurchaseBill({ supplier, items, save, done }: { supplier: Party; items: Item[]; save: (path: string, body: unknown) => Promise<boolean>; done: () => void }) { const [lines, setLines] = useState([newLine()]); const [paid, setPaid] = useState('0'); const total = lines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.price || 0), 0); function edit(index: number, key: keyof PurchaseLine, value: string) { setLines(lines.map((line, i) => i === index ? { ...line, [key]: value } : line)); }
  async function submit(event: FormEvent) { event.preventDefault(); const valid = lines.filter(line => line.name.trim() && Number(line.quantity) > 0 && Number(line.price) >= 0); if (!valid.length) return; const resolved = []; for (const line of valid) { let found = items.find(item => item.name.toLowerCase() === line.name.trim().toLowerCase()); if (!found) { const response = await fetch('/api/inventory/master', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind: 'item', data: { name: line.name.trim(), type: 'RAW_MATERIAL', baseUnit: line.unit, reorderLevel: 0 } }) }); if (!response.ok) return; found = { id: (await response.json()).id } as Item; } resolved.push({ itemId: found.id, quantity: Number(line.quantity), unit: line.unit, unitPricePaise: Math.round(Number(line.price) * 100) }); } const success = await save('/api/inventory/transactions/purchase', { date: today(), supplierId: supplier.id, billNumber: '', lines: resolved, billAmountPaise: Math.round(total * 100), paidAmountPaise: Math.round(Number(paid || 0) * 100) }); if (success) done(); }
  return <form className="im-bill-editor" onSubmit={submit}><div><p className="im-kicker">{supplier.name.toUpperCase()}</p><h2>New purchase bill</h2><p>Add raw materials directly. A new item is added to inventory automatically.</p></div><div className="im-line-head"><span>Item</span><span>Qty</span><span>Unit</span><span>Rate ₹</span><span>Total</span></div>{lines.map((line, index) => <div className="im-purchase-line" key={index}><input list="raw-items" value={line.name} onChange={e => edit(index, 'name', e.target.value)} placeholder="Maida, Sugar, Yeast…" required /><input value={line.quantity} onChange={e => edit(index, 'quantity', e.target.value)} type="number" min="0.01" step="0.01" required /><select value={line.unit} onChange={e => edit(index, 'unit', e.target.value)}><option>kg</option><option>litre</option><option>piece</option></select><input value={line.price} onChange={e => edit(index, 'price', e.target.value)} type="number" min="0" step="0.01" required /><b>{money(Math.round(Number(line.quantity || 0) * Number(line.price || 0) * 100))}</b>{lines.length > 1 && <button type="button" className="im-remove" onClick={() => setLines(lines.filter((_, i) => i !== index))}>×</button>}</div>)}<datalist id="raw-items">{items.filter(item => item.type === 'RAW_MATERIAL').map(item => <option value={item.name} key={item.id} />)}</datalist><button type="button" className="im-text-button" onClick={() => setLines([...lines, newLine()])}>+ Add another item</button><div className="im-bill-total"><label>Payment received now (₹)<input value={paid} onChange={e => setPaid(e.target.value)} type="number" min="0" step="0.01" /></label><strong>Bill total: {money(Math.round(total * 100))}</strong><button>Post bill →</button></div></form>; }
function CustomerWorkspace({ customers, items, save }: { customers: Party[]; items: Item[]; save: (path: string, body: unknown) => Promise<boolean> }) { const [type, setType] = useState<'WHOLESALE' | 'RETAIL'>('WHOLESALE'); const [selected, setSelected] = useState<Party | null>(null); const [creating, setCreating] = useState(false); const [modal, setModal] = useState(false); const list = customers.filter(customer => customer.customerType === type); async function addCustomer(form: FormData) { if (await save('/api/inventory/master', { kind: 'customer', data: { name: form.get('name'), phone: form.get('phone'), contactPerson: form.get('contactPerson'), address: form.get('address'), customerType: type } })) setModal(false); }
  return <div className="im-operational"><div className="im-workspace-head"><div><p className="im-kicker">CUSTOMER DIRECTORY</p><h2>{selected ? selected.name : 'Customer accounts'}</h2></div><button onClick={() => setModal(true)}>+ New {type.toLowerCase()} customer</button></div><div className="im-segmented"><button className={type === 'WHOLESALE' ? 'selected' : ''} onClick={() => { setType('WHOLESALE'); setSelected(null); setCreating(false); }}>Wholesale customers</button><button className={type === 'RETAIL' ? 'selected' : ''} onClick={() => { setType('RETAIL'); setSelected(null); setCreating(false); }}>Retail customers</button></div>{selected ? <section className="im-selected-party"><div className="im-selected-party-head"><div><p className="im-kicker">{type} CUSTOMER ACCOUNT</p><h2>{selected.name}</h2><span>{selected.contactPerson || selected.phone || 'Sales account'}</span></div><button className="im-secondary" onClick={() => { setSelected(null); setCreating(false); }}>← All customers</button></div><div className="im-party-summary"><span>Customer history</span><button onClick={() => setCreating(true)}>+ New bill for {selected.name}</button></div></section> : <div className="im-party-cards">{list.map(customer => <button className="im-party-card" key={customer.id} onClick={() => setSelected(customer)}><span>{customer.name.slice(0, 1)}</span><b>{customer.name}</b><small>{customer.phone || customer.contactPerson || type.toLowerCase()}</small></button>)}{!list.length && <Empty title={`No ${type.toLowerCase()} customers`} copy="Add a customer with the button above." />}</div>}{selected && creating && <QuickSale customer={selected} products={items.filter(item => item.type === 'FINISHED_GOOD')} save={save} done={() => { setCreating(false); setSelected(null); }} />}<Modal open={modal} title={`New ${type.toLowerCase()} customer`} close={() => setModal(false)}><PartyForm kind="customer" submit={addCustomer} /></Modal></div>; }
function QuickSale({ customer, products, save, done }: { customer: Party; products: Item[]; save: (path: string, body: unknown) => Promise<boolean>; done: () => void }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const price = Number(f.get('price')); const qty = Number(f.get('quantity')); if (await save('/api/inventory/transactions/sale', { date: today(), customerId: customer.id, saleType: customer.customerType || 'RETAIL', lines: [{ itemId: f.get('productId'), quantity: qty, unit: f.get('unit'), unitPricePaise: Math.round(price * 100) }], paidAmountPaise: Math.round(Number(f.get('paid') || 0) * 100) })) done(); }
  return <form className="im-bill-editor" onSubmit={submit}><p className="im-kicker">{customer.name.toUpperCase()}</p><h2>Quick sale</h2>{products.length ? <><div className="im-four"><label>Product<select name="productId" required>{products.map(product => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required /></label><label>Rate ₹<input name="price" type="number" min="0" step="0.01" required /></label><label>Paid ₹<input name="paid" type="number" min="0" step="0.01" defaultValue="0" /></label></div><input name="unit" type="hidden" value="piece" /><button>Post sale →</button></> : <p className="im-empty">Add a finished product during production setup before posting sales.</p>}</form>; }
function ProductionHint() { return <section className="im-guard"><h2>Production workspace</h2><p>Use the existing production controls after you add finished products. Purchase and customer workflows have been streamlined first.</p></section>; }
function ExpenseForm({ save }: { save: (path: string, body: unknown) => Promise<boolean> }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await save('/api/inventory/transactions/expense', { date: f.get('date'), category: f.get('category'), amountPaise: Math.round(Number(f.get('amount')) * 100), note: f.get('note') }); } return <form className="im-form im-transaction" onSubmit={submit}><p className="im-kicker">DAILY OPERATING COST</p><h2>Record expense</h2><label>Date<input name="date" type="date" defaultValue={today()} /></label><label>Category<select name="category"><option>Employee wages</option><option>Electricity</option><option>Fuel</option><option>Rent</option><option>Transport</option><option>Maintenance</option><option>Miscellaneous</option></select></label><label>Amount (₹)<input name="amount" type="number" min="0" step="0.01" required /></label><label>Notes<textarea name="note" rows={3} /></label><button>Post expense →</button></form>; }
function DateStrip({ date, setDate }: { date: string; setDate: (date: string) => void }) { const shift = (amount: number) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + amount); setDate(next.toISOString().slice(0, 10)); }; return <div className="im-date-strip"><button onClick={() => shift(-1)}>← Previous day</button><label><span>Purchase date</span><input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button onClick={() => shift(1)}>Next day →</button></div>; }
function BillCard({ bill }: { bill: Bill }) { return <article className="im-bill-card"><div><b>{bill.supplier}</b><span>{bill.billNumber}</span></div><ul>{bill.lines.map((line, index) => <li key={index}>{line.name} <small>{line.quantity} {line.unit}</small><strong>{money(line.totalPaise)}</strong></li>)}</ul><footer><span>Paid {money(bill.paidAmountPaise)}</span><span>Pending <b>{money(bill.pendingPaise)}</b></span><strong>{money(bill.billAmountPaise)}</strong></footer></article>; }
function PartyForm({ kind, submit }: { kind: 'supplier' | 'customer'; submit: (data: FormData) => void }) { return <form className="im-modal-form" onSubmit={event => { event.preventDefault(); submit(new FormData(event.currentTarget)); }}><label>Name<input name="name" required autoFocus /></label><label>Phone<input name="phone" inputMode="tel" /></label><label>Contact person<input name="contactPerson" /></label><label>Address<textarea name="address" rows={2} /></label><button>Save {kind} →</button></form>; }
function Modal({ open, title, close, children }: { open: boolean; title: string; close: () => void; children: React.ReactNode }) { if (!open) return null; return <div className="im-modal-backdrop" onMouseDown={close}><section className="im-modal" onMouseDown={event => event.stopPropagation()}><button className="im-modal-close" onClick={close}>×</button><p className="im-kicker">QUICK CREATE</p><h2>{title}</h2>{children}</section></div>; }
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="im-empty"><b>{title}</b><p>{copy}</p></div>; }
