'use client';
import { FormEvent, useEffect, useState } from 'react';
import type { Item, Party } from '@/lib/inventory/types';

const money = (p = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(p / 100);
const day = () => new Date().toISOString().slice(0, 10);
type Post = (path: string, body: unknown) => Promise<boolean>;
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="im-modal-backdrop" role="dialog"><div className="im-modal"><button className="im-modal-close" onClick={close}>×</button><h2>{title}</h2>{children}</div></div>; }
function PartyCard({ party, onOpen }: { party: Party; onOpen: () => void }) { return <button className="im-party-card" onClick={onOpen}><span className="im-avatar">{party.name.slice(0, 1).toUpperCase()}</span><strong>{party.name}</strong><small>{party.phone || party.contactPerson || 'Open account'}</small><b>Open →</b></button>; }
function PartyModal({ kind, post, close }: { kind: 'supplier' | 'customer'; post: Post; close: () => void }) { async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); if (await post('/api/inventory/master', { kind, data })) close(); } return <Modal title={`New ${kind}`} close={close}><form className="im-form im-modal-form" onSubmit={submit}><label>Name<input name="name" autoFocus required /></label><label>Phone<input name="phone" inputMode="tel" /></label><label>Contact person<input name="contactPerson" /></label><label>Address<textarea name="address" rows={2} /></label>{kind === 'customer' && <label>Customer type<select name="customerType"><option value="WHOLESALE">Wholesale</option><option value="RETAIL">Retail</option></select></label>}<button>Save {kind} →</button></form></Modal>; }
export function SupplierDirectory({ suppliers, post, select }: { suppliers: Party[]; post: Post; select: (party: Party) => void }) { const [modal, setModal] = useState(false); return <section><div className="im-section-actions"><div><p className="im-kicker">PURCHASE PARTNERS</p><h2 className="im-page-title">Suppliers</h2></div><button className="im-primary" onClick={() => setModal(true)}>+ New supplier</button></div><div className="im-party-grid">{suppliers.map(supplier => <PartyCard party={supplier} onOpen={() => select(supplier)} key={supplier.id} />)}{!suppliers.length && <div className="im-guard"><h2>No suppliers yet</h2><p>Add one here, then create purchase bills directly from its card.</p></div>}</div>{modal && <PartyModal kind="supplier" post={post} close={() => setModal(false)} />}</section>; }
export function CustomerDirectory({ customers, post }: { customers: Party[]; post: Post }) { const [modal, setModal] = useState(false); const wholesale = customers.filter(customer => customer.customerType === 'WHOLESALE'); const retail = customers.filter(customer => customer.customerType !== 'WHOLESALE'); return <section><div className="im-section-actions"><div><p className="im-kicker">CUSTOMER ACCOUNTS</p><h2 className="im-page-title">Customers</h2></div><button className="im-primary" onClick={() => setModal(true)}>+ New customer</button></div><CustomerGroup title="Wholesale" customers={wholesale} /><CustomerGroup title="Retail" customers={retail} />{modal && <PartyModal kind="customer" post={post} close={() => setModal(false)} />}</section>; }
function CustomerGroup({ title, customers }: { title: string; customers: Party[] }) { return <div className="im-customer-group"><div className="im-panel-title"><h2>{title}</h2><span>{customers.length} customers</span></div><div className="im-party-grid">{customers.map(customer => <PartyCard party={customer} onOpen={() => undefined} key={customer.id} />)}{!customers.length && <p className="im-muted">No {title.toLowerCase()} customers added yet.</p>}</div></div>; }
export function PurchaseWorkspace({ suppliers, items, post, initialSupplier, refresh }: { suppliers: Party[]; items: Item[]; post: Post; initialSupplier?: Party; refresh: () => Promise<void> }) { const [supplier, setSupplier] = useState<Party | undefined>(initialSupplier); const [modal, setModal] = useState(false); const [date, setDate] = useState(day()); const [bills, setBills] = useState<Array<{ id: string; billNumber: string; billAmountPaise: number; outstandingPaise: number; lines: Array<{ itemName: string; quantity: number; unit: string }> }>>([]); const [itemName, setItemName] = useState(''); const [itemId, setItemId] = useState(''); const [quantity, setQuantity] = useState(''); const [unit, setUnit] = useState('kg'); const [price, setPrice] = useState(''); const [billNumber, setBillNumber] = useState(''); const [paid, setPaid] = useState('0');
  useEffect(() => { setSupplier(initialSupplier); }, [initialSupplier]); useEffect(() => { if (!supplier) return; fetch(`/api/inventory/purchases?date=${date}&supplierId=${supplier.id}`).then(response => response.ok ? response.json() : []).then(setBills); }, [date, supplier]);
  function chooseItem(value: string) { setItemName(value); const match = items.find(item => item.name.toLowerCase() === value.trim().toLowerCase()); setItemId(match?.id || ''); if (match) setUnit(match.baseUnit); }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!supplier) return; let resolvedId = itemId; if (!resolvedId && itemName.trim()) { const response = await fetch('/api/inventory/master', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind: 'item', data: { name: itemName.trim(), type: 'RAW_MATERIAL', baseUnit: unit, reorderLevel: 0 } }) }); if (!response.ok) return; resolvedId = (await response.json()).id; } const amount = Math.round(Number(quantity) * Number(price) * 100); const bill = Number((document.querySelector('[name=billAmount]') as HTMLInputElement)?.value || amount / 100); const ok = await post('/api/inventory/transactions/purchase', { date, supplierId: supplier.id, billNumber, lines: [{ itemId: resolvedId, quantity: Number(quantity), unit, unitPricePaise: Math.round(Number(price) * 100) }], billAmountPaise: Math.round(bill * 100), paidAmountPaise: Math.round(Number(paid) * 100) }); if (ok) { setItemName(''); setItemId(''); setQuantity(''); setPrice(''); setBillNumber(''); setPaid('0'); const response = await fetch(`/api/inventory/purchases?date=${date}&supplierId=${supplier.id}`); if (response.ok) setBills(await response.json()); } }
  if (!supplier) return <div><div className="im-section-actions"><div><p className="im-kicker">PURCHASE DESK</p><h2 className="im-page-title">Choose a supplier</h2></div><button className="im-primary" onClick={() => setModal(true)}>+ New supplier</button></div><div className="im-party-grid">{suppliers.map(row => <PartyCard party={row} onOpen={() => setSupplier(row)} key={row.id} />)}</div>{modal && <PartyModal kind="supplier" post={post} close={() => setModal(false)} />}</div>;
  return <div><div className="im-section-actions"><div><p className="im-kicker">PURCHASE DESK · {supplier.name.toUpperCase()}</p><h2 className="im-page-title">Purchase bills</h2></div><button className="im-secondary" onClick={() => setSupplier(undefined)}>← All suppliers</button></div><div className="im-date-toolbar"><label>View date<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><span>{bills.length} bills · {money(bills.reduce((sum, bill) => sum + bill.billAmountPaise, 0))} spent</span></div><div className="im-bill-layout"><form className="im-form im-bill-form" onSubmit={submit}><p className="im-kicker">NEW BILL</p><h2>Quick entry</h2><label>Item name<input list="purchase-items" value={itemName} onChange={event => chooseItem(event.target.value)} placeholder="Type Maida, Sugar…" required /><datalist id="purchase-items">{items.map(item => <option value={item.name} key={item.id} />)}</datalist></label><div className="im-three"><label>Quantity<input type="number" min="0.01" step="0.01" value={quantity} onChange={event => setQuantity(event.target.value)} required /></label><label>Unit<select value={unit} onChange={event => setUnit(event.target.value)}><option>kg</option><option>litre</option><option>piece</option></select></label><label>Unit price (₹)<input type="number" min="0" step="0.01" value={price} onChange={event => setPrice(event.target.value)} required /></label></div><div className="im-two"><label>Bill total (₹)<input name="billAmount" type="number" min="0" step="0.01" placeholder="Auto from lines" /></label><label>Amount paid (₹)<input type="number" min="0" step="0.01" value={paid} onChange={event => setPaid(event.target.value)} /></label></div><label>Bill number<input value={billNumber} onChange={event => setBillNumber(event.target.value)} /></label><button>Post bill →</button></form><div className="im-bills"><div className="im-panel-title"><h2>{date === day() ? "Today's bills" : `Bills on ${date}`}</h2><span>{bills.length} bills</span></div>{bills.map((bill, index) => <article className="im-bill-card" key={bill.id}><div><b>Bill {bill.billNumber || `#${bills.length - index}`}</b><small>{bill.lines.map(line => `${line.itemName} · ${line.quantity} ${line.unit}`).join(', ')}</small></div><strong>{money(bill.billAmountPaise)}<small>{bill.outstandingPaise ? `${money(bill.outstandingPaise)} pending` : 'Paid'}</small></strong></article>)}{!bills.length && <EmptyPurchase />}</div></div></div>; }
function EmptyPurchase() { return <div className="im-empty"><b>No bills for this date</b><p>Post the first bill using quick entry.</p></div>; }
